# Introduction to Deep Learning

## What is Deep Learning?

Deep Learning is a subset of artificial intelligence (AI) and machine learning (ML) that focuses on using neural networks with many layers to analyze and learn from data. These neural networks, often referred to as deep neural networks, are designed to automatically and adaptively learn patterns from large amounts of data without explicit programming.

### Key Points:
- **Neural Networks**: Computation models inspired by the human brain's structure and function.
- **Layers**: Multiple layers of neurons that help in extracting features from raw data.
- **Training**: The process of adjusting the model parameters to minimize prediction errors using large datasets.

# Introduction to Neurons and Neural Networks

## Neurons

A **neuron** is the fundamental unit of a neural network, inspired by biological neurons in the human brain. It performs the following functions:

- **Input Reception**: Neurons receive input signals from other neurons or external sources.
- **Weighted Sum**: Each input is multiplied by a weight, and these weighted inputs are summed up.
- **Activation Function**: The sum is passed through an activation function to determine the neuron's output.

### Components of a Neuron:

- **Inputs**: Values fed into the neuron.
- **Weights**: Parameters that scale the inputs.
- **Bias**: A constant added to the weighted sum.
- **Activation Function**: A function that transforms the weighted sum to the output.

### Activation Function:

The activation function introduces non-linearity into the model, allowing it to learn complex patterns. Common activation functions include:

- **Sigmoid**: `σ(x) = 1 / (1 + e^(-x))`
- **ReLU**: `ReLU(x) = max(0, x)`
- **Tanh**: `tanh(x) = (e^x - e^(-x)) / (e^x + e^(-x))`

## Neural Networks

A **neural network** is a collection of interconnected neurons organized into layers. It consists of:

- **Input Layer**: Receives the initial data.
- **Hidden Layers**: Intermediate layers where computations are performed. Each neuron in a hidden layer receives inputs from neurons in the previous layer and sends outputs to neurons in the next layer.
- **Output Layer**: Produces the final result or prediction.

### Structure of a Neural Network:

```plaintext
Input Layer      Hidden Layers      Output Layer
  [ x1 ]            [ h1 ]             [ y1 ]
  [ x2 ]  --->      [ h2 ]  --->       [ y2 ]
  [ x3 ]            [ h3 ]             [ y3 ]


# Introduction to PyTorch

## What is PyTorch?

PyTorch is an open-source deep learning framework developed by Facebook's AI Research lab. It provides a flexible and intuitive way to build and train neural networks. PyTorch is popular for its dynamic computation graph, which makes it easier to work with complex models and debug your code.

### Key Components of PyTorch

1. **Tensors**
   - **Definition**: Tensors are the fundamental building blocks in PyTorch. They are multi-dimensional arrays similar to NumPy arrays but with additional capabilities for GPU acceleration.
   - **Usage**: Used for storing and manipulating data. Tensors can be created from lists, NumPy arrays, or directly from PyTorch functions.

In [3]:
import torch

print(torch.__version__)

2.4.0+cu124


In [4]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
#vector
vector = torch.tensor([
    [2,3],
    [4,5]
])
vector

tensor([[2, 3],
        [4, 5]])

In [8]:
vector.ndim

2

In [9]:
vector.shape

torch.Size([2, 2])

In [10]:
### Creating range of tensor and tensor-like
one_to_ten = torch.arange(start = 1,end = 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#creating tensorlike
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [12]:
!nvidia-smi

Wed Aug 14 05:26:55 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.31.01              Driver Version: 560.81         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   42C    P5             20W /   45W |     554MiB /   8188MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [13]:
# flaot 32 tensor on cpu
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                              device='cpu',
                              requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [14]:
# flaot 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                              device='cuda',
                              requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [15]:
float_32_tensor.dtype

torch.float32

In [16]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [17]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [18]:
int_32_tensor = torch.tensor([3,6,9],dtype= torch.long,device='cuda')
int_32_tensor

tensor([3, 6, 9], device='cuda:0')

In [19]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')